# -*- coding: utf-8 -*-
"""Ad class2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198HLjikeYMjwX1nQReGzTHZ6gLJd8jmN
"""

list = ["apple", "banana", "cherry"]
print(list)

a = [1,2,3]
b = [1,2,3]
c= a+b
print(c)

a = [1,2,3,4,5,6,7,8,9,0]
b = a[1:]
print(b)

a = [1,2,3,4,5,6,7,8,9,0]
b = a[1:5]
print(b)

a = [1,2,12,4,5,6,7,8,9,0]
a.sort()
print(a)

age = int(input("Enter age: "))
studyhours = int(input("Enter no of hours study: "))

if age<10 and studyhours<10:
    print("marks:less than 50")

elif age<10 and studyhours>10:
    print("marks:less than 60")

elif age>10 and studyhours<10:
    print("marks:less than 70")

elif age>10 and studyhours>10:
  print("full marks")

d = {1: "Geeks", 2:"For", 3:"Geeks"}
print(d)

"""# #Demo"""

# Demo for int

my_int =42
print("Original integer: ",my_int)

# Demo for list

my_list = [1,"hello",3.14,True]
print(my_list)


# Adding an element to the list

my_list.append("world")
print(my_list)

# Removing an element from the list

my_list.remove(3.14)
print(my_list)

# Demo for tuple

my_tuple = (1,"apple",3.14,True)
print(my_tuple)

#Accessing tuple

print("First tuple: ",my_tuple[0])
print("Last tuple: ",my_tuple[-1])

#for loop

for i in range(1,6):
  print(i,end=" ")

#while loop

i=1
while i<=5:
  print(i,end=" ")
  i+=1

#if condition

number = int(input("enter your number: "))

if number>0:
  print("positive")
elif number<0:
  print("negative")
else:
  print("zero")

#function

def greet(name):
  print("hello",name)
greet("Alice")