# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/198HLjikeYMjwX1nQReGzTHZ6gLJd8jmN
"""
# print list


list = ["apple", "banana", "cherry"]
print(list)

#list

a = [1,2,3]
b = [1,2,3]
c= a+b
print(c)


#Slicing
a = [1,2,3,4,5,6,7,8,9,0]
b = a[1:]
print(b)

#Slicing
a = [1,2,3,4,5,6,7,8,9,0]
b = a[1:5]
print(b)

#Sorting
a = [1,2,12,4,5,6,7,8,9,0]
a.sort()
print(a)

#PRint marks
age = int(input("Enter age: "))
studyhours = int(input("Enter no of hours study: "))

if age<10 and studyhours<10:
    print("marks:less than 50")

elif age<10 and studyhours>10:
    print("marks:less than 60")

elif age>10 and studyhours<10:
    print("marks:less than 70")

elif age>10 and studyhours>10:
  print("full marks")
